### ISSUE TITLE
Can't build project with Swift 3

### ISSUE THREAD

**Issue by Relax594** [tbaranes/DOButton#4]
I'm using the latest version of the pod but i just can't build it within my app..

<img width="763" alt="bildschirmfoto 2016-10-14 um 16 37 51" src="https://cloud.githubusercontent.com/assets/22765758/19391387/a6027810-922c-11e6-8e9d-13232e7793e1.png">

**Comment by tbaranes** [comment]
Which version of `CocoaPods` and `DOButton` are you using?

**Comment by Relax594** [comment]
Latest stable release of CocoaPods and DOButton 1.2.0

**Comment by tbaranes** [comment]
The last stable `CocoaPods` version is not working well when used with swift 3, can you try to use the last beta release candidate?

**Comment by Relax594** [comment]
I updated to the latest rc now and still same issues. Maybe i try to reinstall my pods, give me a minute.

**Comment by Relax594** [comment]
Working fine now, thanks! Cleared my pod and re-installed all pods with the latest rc.
